### ISSUE TITLE
big-test page does not successfully emphasize inside blockquote

### ISSUE THREAD

**Issue by dHannasch** [maxpou/gatsby-starter-morning-dew#114]
https://maxpou.github.io/gatsby-starter-morning-dew/big-test#blockquotes has
<pre>
Oh, you can *put* **Markdown** into a blockquote.
</pre>
but the *put* is not actually emphasized in the blockquote. (Possibly an underlying limitation?)

One easy solution would be to just give up on italicizing blockquotes: https://github.com/dHannasch/gatsby-starter-morning-dew/commit/326ebc8da4782e86dbda46dd568527c3c02170b9

**Comment by maxpou** [comment]
Hey  @dHannasch,
thanks for spotting this issue. 
You right, all blockquotted posts are in italic by default.

However, I like the actual behavior. So, I'll probably leave this as it and remove the `*put*` in the big-test post.

**Comment by dHannasch** [comment]
Setting things up to silently fail seems worse. If you're planning to stick with this, it seems like it would be better to *include* the "*put*" on the big-test page, with a note pointing out that emphasis in blockquotes is not supported.

Something like:
https://github.com/maxpou/gatsby-starter-morning-dew/blob/master/content/posts/2018-01-03-Big-Sample-Post/index.md#Blockquotes
```no-highlight
> Oh, you can *put* **Markdown** into a blockquote.
```

Note that `*emphasis*`/*emphasis* inside a blockquote is not supported; see *put* above.

**Comment by maxpou** [comment]
hey @dHannasch , I removed the emphasis bloc in the markdown file.
I don't think it's needed to write "emphasis inside a blockquote is not supported" since the whole block has this style :)

**Comment by dHannasch** [comment]
(shrug) It's your decision.

Just checking, if I find a way to allow text to be emphasized (that is, de-italicized) within an italicized blockquote (such as in the APA style https://apastyle.apa.org/style-grammar-guidelines/italics-quotations/italics), so that emphasis functionality is still available (that is, asterisks do something) within a blockquote, would you be interested in having that? (To be clear, I haven't actually figured out how to do that.)
