### ISSUE TITLE
How to change logo

### ISSUE THREAD

**Issue by amanur38** [maxpou/gatsby-starter-morning-dew#45]
How to change header home menu logo. Here add a emoji , how to add logo.

**Comment by maxpou** [comment]
Hey,

This is not supported at the moment. 
What you can do is:

1. In `siteConfig.js`, remove
```js
    {
      label: '🏡',
      url: '/',
    },
```
2. in `src/components/Header.js`, add your logo. You can hardcode it. You will probably need to write some css!

**Comment by maxpou** [comment]
Hello @Amanur38,
this is now possible :)
https://maxpou.github.io/gatsby-starter-morning-dew/
