### ISSUE TITLE
Image not show in markdown file.

### ISSUE THREAD

**Issue by xeusteerapat** [maxpou/gatsby-starter-morning-dew#54]
Hello @maxpou ,
        I've tried to add image in markdown but it didn't work. Please see picture below.
<img width="1019" alt="Screenshot 2019-03-17 17 28 07" src="https://user-images.githubusercontent.com/37167919/54489007-800e4500-48da-11e9-9440-cdf5d52d0501.png">
<img width="722" alt="Screenshot 2019-03-17 17 31 51" src="https://user-images.githubusercontent.com/37167919/54489016-90bebb00-48da-11e9-9774-58e81d83cc1b.png">

Thank you for help.
Teerapat

**Comment by maxpou** [comment]
Hey @xeusteerapat ,
 I don't understand because in the following folder `content/posts/2018-09-29-a-post-with-images`, the image is showing.

Do you have a repository where I can take a look at your issue?
Cheers, Max
