### ISSUE TITLE
Generating PostPreviewImages does not work with yaml > 1.0.0

### ISSUE THREAD

**Issue by JeroenKnoops** [maxpou/gatsby-starter-morning-dew#62]
`yaml` has changed their main API. 

When using 1.6.0 you will get this error:
```
npm run generatePostPreviewImages

> gatsby-starter-morning-dew@0.0.0-development generatePostPreviewImages /private/tmp/gatsby-blog
> node ./scripts/generatePostPreviewImages.js

/private/tmp/gatsby-blog/scripts/generatePostPreviewImages.js:42
      const data = yaml.parse(frontmatter)
                        ^

TypeError: Cannot read property 'parse' of undefined
    at readFile (/private/tmp/gatsby-blog/scripts/generatePostPreviewImages.js:42:25)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
```

**Comment by fpigeonjr** [comment]
awesome, I am getting this issue on my site. How do I upgrade to the latest version @maxpou?
Thanks for your assistance.

**Comment by maxpou** [comment]
Hey @fpigeonjr,

Just saw your message.
Well, Gatsbyjs starter are kinda based on code duplication.

If you want to bump your website to the latest version, you have 2 options:
* if you haven't changed the `src` folder:  remove your `src` folder and copy the one from this folder.
* if you made some quick changes, you can select the things you want with a `git diff` (good luck 😬)
* you can also switch to a Gatsby Theme. (https://www.gatsbyjs.org/blog/2018-11-11-introducing-gatsby-themes/)
