### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by wrannet** [maxpou/gatsby-starter-morning-dew#81]
Hi maxpou, I'm sure you want to keep this repo public, but if you have any interest in a paid version down the road I'd love to have it on [SugarKubes](https://sugarkubes)!

**Comment by maxpou** [comment]
Hey @wrannet,

Thanks for reaching out.
At the moment, I don't plan to remove the MIT License of this project.
But, I believe, with 30 000 $USD I could change my mind.

Cheers,
Max.
