### ISSUE TITLE
Theme Instructions

### ISSUE THREAD

**Issue by fpigeonjr** [maxpou/gatsby-starter-morning-dew#86]
@maxpou,
How does one upgrade ones blog from a `starter` to a `theme`?
Also how would one just start new with your `theme`?

❤️Thanks for your guidance and love your work!

**Comment by maxpou** [comment]
Hey Frank!

Hmmm I don't have doc for migration at the moment. 
But you can check:
* how I migrate my website to a theme: https://github.com/maxpou/maxpou.fr/pull/34/files
. I deleted whole `src` folder, updated `package.json`, removed `gatsby-node.js` and `gatsby-config.js`.
* https://github.com/maxpou/gatsby-groot. It's a minimalist website based on the theme.

Let me know if you've more questions :)

**Comment by fpigeonjr** [comment]
✔thanks @maxpou for the quick reply! I will review later and give it a shot.

I am concerned that my site is falling behind all the goodness that comes from your upstream starter/theme.

I understand that if I change it from a starter to a theme than I can pull in the changes from upstream so that is my intent.

Also wondering if someone starts fresh blog from the theme, what are the instructions for that setup?

**Comment by ChengSian** [comment]
> ✔thanks @maxpou for the quick reply! I will review later and give it a shot.
> 
> I am concerned that my site is falling behind all the goodness that comes from your upstream starter/theme.
> 
> I understand that if I change it from a starter to a theme than I can pull in the changes from upstream so that is my intent.
> 
> Also wondering if someone starts fresh blog from the theme, what are the instructions for that setup?

Can you start fresh blog from the theme?  I can't. Maybe that for newbie is too hard😂 perhaps I'll build a gatsby site from scratch for a good learning path......

**Comment by maxpou** [comment]
Hey @ChengSian,

Yes you can!
See:
* demo: https://groot-morning-dew.netlify.com/
* code: https://github.com/maxpou/gatsby-groot/

I hope you will find everything there useful :)
edit: I'll update it to the latest version this afternoon

**Comment by ChengSian** [comment]
> Hey @ChengSian,
> 
> Yes you can!
> See:
> 
> * demo: https://groot-morning-dew.netlify.com/
> * code: https://github.com/maxpou/gatsby-groot/
> 
> I hope you will find everything there useful :)
> edit: I'll update it to the latest version this afternoon

Does this mean I don't need to follow the instruction of the below link to install a theme?
https://github.com/maxpou/gatsby-starter-morning-dew#installation-theme

**Comment by maxpou** [comment]
you have 2 way of using it:
* as a starter
* as a theme

the project I sent you use this project as a gatsby theme. All the steps are already in so, feel free to git clone it, everything should works :)

**Comment by ChengSian** [comment]
Thank you for all your hard work on this😊
