### ISSUE TITLE
Chain Icon next to headers in markdown article

### ISSUE THREAD

**Issue by richard5635** [maxpou/gatsby-starter-morning-dew#97]
Hi! This is more of a question rather than a bug.
Every time I make a new header in a markdown page, there is always a link icon appearing before it.
Is there a way to remove it? One example is this link icon next to "Hello World" in the picture below.

<img width="656" alt="Screen Shot 2019-12-18 at 11 47 03" src="https://user-images.githubusercontent.com/29296883/71051741-9fe5d880-218c-11ea-9143-eab99c54943b.png">

Thanks!

**Comment by maxpou** [comment]
Hey Richard!

This icon is an anchor. It can be useful if you want to share a specific part of your blogpost.
Example: https://maxpou.github.io/gatsby-starter-morning-dew/using-mdx#how-to

If you want to remove it, you've a few option:
* Hide the anchor with css: `a.anchor { display: none; }`. So you can keep the link but now you need to use the inspector to get the link.
* remove this feature. In `gatsby-config.js`, remove line 60: `{ resolve: 'gatsby-remark-autolink-headers' },`. Remove also this dependency in `package.json`.

I hope it will help you
